export const industryOptions = [
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'arts-entertainment', label: 'Arts and Entertainment' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'banking-financial', label: 'Banking and Financial Services' },
  { value: 'construction', label: 'Construction' },
  { value: 'consulting', label: 'Consulting' },
  { value: 'consumer-goods', label: 'Consumer Goods' },
  { value: 'education', label: 'Education' },
  { value: 'energy-utilities', label: 'Energy and Utilities' },
  { value: 'food-beverages', label: 'Food and Beverages' },
  { value: 'government-public', label: 'Government and Public Sector' },
  { value: 'healthcare-life-sciences', label: 'Healthcare and Life Sciences' },
  { value: 'information-technology', label: 'Information Technology' },
  { value: 'insurance', label: 'Insurance' },
  { value: 'legal-services', label: 'Legal Services' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'non-profit', label: 'Non-Profit' },
  { value: 'pharmaceuticals', label: 'Pharmaceuticals' },
  { value: 'real-estate', label: 'Real Estate' },
  { value: 'retail-wholesale', label: 'Retail and Wholesale' },
  { value: 'telecommunications', label: 'Telecommunications' },
  { value: 'transportation-logistics', label: 'Transportation and Logistics' },
  { value: 'travel-hospitality', label: 'Travel and Hospitality' },
  { value: 'other', label: 'Other' },
];

export const workOptions = [
  { value: 'administration', label: 'Administration' },
  { value: 'customer-service', label: 'Customer Service' },
  { value: 'engineering', label: 'Engineering' },
  { value: 'executive-management', label: 'Executive Management' },
  { value: 'finance-accounting', label: 'Finance and Accounting' },
  { value: 'human-resources', label: 'Human Resources' },
  { value: 'information-technology', label: 'Information Technology' },
  { value: 'legal', label: 'Legal' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'operations', label: 'Operations' },
  { value: 'product-development', label: 'Product Development' },
  { value: 'quality-assurance', label: 'Quality Assurance' },
  { value: 'sales', label: 'Sales' },
  { value: 'supply-chain-management', label: 'Supply Chain Management' },
  { value: 'other', label: 'Other' },
];

export const organizationSizeOptions = [
  { value: '1', label: '1' },
  { value: '2-5', label: '2 to 5' },
  { value: '6-10', label: '6 to 10' },
  { value: '11-50', label: '11 to 50' },
  { value: '51-100', label: '51 to 100' },
  { value: '101-250', label: '101 to 250' },
];
